# Generated by Django 2.0.4 on 2018-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_group_create_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_create_permission',
            field=models.BooleanField(default=0),
        ),
    ]
