# Generated by Django 2.0.4 on 2018-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_connect_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='invite_key',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
