# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time to publish')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='time added')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
