# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        ('problem', '0002_auto_20170809_1325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Accepted'), (7, 'Pending')], default=7)),
                ('info', models.CharField(max_length=65535)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='time added')),
                ('judge_start_time', models.DateTimeField(null=True)),
                ('judge_finish_time', models.DateTimeField(null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
