# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='length',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.CharField(blank=True, max_length=65535),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judge_finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='judge_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
