# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', markdownx.models.MarkdownxField(blank=True, max_length=1000)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('running_task_number', models.IntegerField(default=0)),
                ('cpu_core', models.IntegerField(default=1)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('act_time', models.DateTimeField(auto_now=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
