# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 10:08
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
